### ISSUE TITLE
Renames .strings files into .xib and .storyboard for projects with Base localization

### ISSUE THREAD

**Issue by lazarev** [venmo/synx#68]
#63 fix does not supports base localization (by default from Xcode 5). This type of localization uses ".strings" files to collect localizable strings for .xib and .storyboard files.

If I have structure like this:
Base.lproj/myview.xib
en.lproj/myview.strings
ru.lproj/myview.strings

after synx I get:
Base.lproj/myview.xib
en.lproj/myview.xib
ru.lproj/myview.xib

Localization tables are just renamed. To fix this synx just shouldn't rename this files but keep their original names.

**Comment by erwald** [comment]
I have the same issue, and am, surprisingly, having trouble repairing it manually. If I rename the files back to `.strings`, Xcode won't let me insert them to the correct place in the project, and, moreover, it won't let me remove any references to the deleted files.

How did you go about fixing this @lazarev? It took me some days before I noticed, so I would rather not return to a previous commit.

**Comment by isair** [comment]
+1

**Comment by Mazyod** [comment]
@erwald Just a thought: Did you check the encoding of the `strings` file? It may have changed in the process to something other than the required encoding `UTF-16` (I think it's required to be that, at least).

**Comment by erwald** [comment]
@Mazyod Do you mean in order to re-add them? I think it's UTF-8 now, but it also works now again. I don't remember exactly what I had to do, but I think it was just another half an hour of fiddling in Xcode that did it.

**Comment by Mazyod** [comment]
@erwald Oh, got it. Yeah, I thought it was a requirement, but it seems to just be a best practice, it is not actually enforced. From Apple docs:

> Note: It is recommended that you save strings files using the UTF-16 encoding, which is the default encoding for standard strings files.

**Comment by radex** [comment]
Ah, same issue here. Does the fix in #77 work well?

**Comment by eugenpirogoff** [comment]
Same issue here.

**Comment by sxmichaels** [comment]
This is still a problem in the latest version; it makes synx totally unusable for apps with localization.

**Comment by beseder42** [comment]
Any progress possible on this? Still not useable on localized Projects!

**Comment by MrNickBarker** [comment]
We fixed this in our project like this:
1. Select the storyboard/xib
2. Un-tick the languages in the localisation panel that have been converted from .strings to .storyboard/.xib. Make sure that the "Delete localized resources from disk" is **not** checked in the popup.
3. In Finder open the language project folder (de.lproj, fr.lproj or whatever) and rename the .storyboard/.xib files back to .strings
4. Back in Xcode select the storyboard/xib and add re-add the localisations. Make sure to select the option to use the existing file in the popup.

**Comment by pschneider** [comment]
@MrNickBarker 's solution worked for us, too. Thanks!

**Comment by tylermilner** [comment]
This issue is still present in the current version. Unfortunately, I didn't know about this before an app update went live and it broke localization in my app for thousands of our Spanish and French users. While it's nice that there is a work around to get things working again, Synx shouldn't be doing this in the first place.

**Comment by NikKovIos** [comment]
MrNickBarker's answer works, but it's poor that the issue still presents.

**Comment by numen31337** [comment]
Same issue here, noticed it too late and already done a lot of changes in the project to just reverse a commit. This was the last time for us when we were using this utility. This is unacceptable for the apps that are in production.

**Comment by eugenpirogoff** [comment]
@numen31337 

a friendly advice: cool down, its an FOSS project. take it or leave it. no need for harsh words here. and yes I ran into the same issue.

**Comment by seasox** [comment]
I ran into the same issue, was able to fix it using the diff of my app's project.pbxproj. Would be great to see a fix in an upcoming release.
